# =====================================================
# Super Magic 配置文件
# =====================================================
# 重要安全提示:
# 1. 敏感的模型ID（如 ep-xxxxxxxxxx 格式的ID）应该只在 .env 文件中定义
# 2. 配置文件中应该使用人类可读的默认值（如 doubao-pro-32k）
# 3. 真实的模型ID应该通过环境变量在运行时注入
# 4. 此文件会被提交到Git，不要在此文件中暴露任何敏感信息
# =====================================================

browser:
  headless: ${BROWSER_HEADLESS:-false}
  cookies_file: ${BROWSER_COOKIES_FILE:-.browser/cookies.json}

# LLM API 通用配置
llm:
  api_timeout: ${LLM_API_TIMEOUT:-600}
  api_max_retries: ${LLM_API_MAX_RETRIES:-3}

agent:
  enable_multi_tool_calls: ${AGENT_ENABLE_MULTI_TOOL_CALLS:-false}
  enable_parallel_tool_calls: ${AGENT_ENABLE_PARALLEL_TOOL_CALLS:-false}
  parallel_tool_calls_timeout: ${AGENT_PARALLEL_TOOL_CALLS_TIMEOUT:-None}
  safety_checker_model_id: ${AGENT_SAFETY_MODEL_ID:-gpt-4.1}

# 图片生成服务配置
image_generator:
  api_url: ${IMAGE_GENERATOR_API_URL:-https://i-magic-service-pre.letsmagic.cn/api/chat}
  api_key: ${IMAGE_GENERATOR_API_KEY}

# 模型配置
models:
  # LLM模型
  claude-3.7:
    api_key: "${CLAUDE_API_KEY}"
    api_base_url: "${CLAUDE_API_BASE_URL:-https://api.anthropic.com/v1}"
    name: "${CLAUDE_MODEL:-claude-3-7-sonnet}"
    type: "llm"
    supports_tool_use: true
    provider: "openai"
    max_tokens: 64000
    context_length: 200000
    temperature: 0.7

  claude-3.7-cache:
    api_key: "${CLAUDE_CACHE_API_KEY}"
    api_base_url: "${CLAUDE_CACHE_API_BASE_URL:-https://brconnector.letsmagic.cc/v1}"
    name: "${CLAUDE_CACHE_MODEL:-claude-3-7-sonnet}"
    type: "llm"
    supports_tool_use: true
    provider: "openai"
    max_tokens: 64000
    context_length: 200000
    temperature: 0.7

  deepseek-chat:
    api_key: "${DEEPSEEK_API_KEY}"
    api_base_url: "${DEEPSEEK_API_BASE_URL:-https://api.deepseek.com/v1}"
    name: "${DEEPSEEK_MODEL:-deepseek-chat}"
    type: "llm"
    supports_tool_use: true
    provider: "openai"
    max_tokens: 16000
    context_length: 32000
    temperature: 0.7

  deepseek-reasoner:
    api_key: "${DEEPSEEK_API_KEY}"
    api_base_url: "${DEEPSEEK_API_BASE_URL:-https://api.deepseek.com/v1}"
    name: "${DEEPSEEK_REASONER_MODEL:-deepseek-reasoner}"
    type: "llm"
    supports_tool_use: true
    provider: "openai"
    max_tokens: 16000
    context_length: 32000
    temperature: 0.7

  gpt-4o:
    api_key: "${OPENAI_API_KEY}"
    api_base_url: "${OPENAI_API_BASE_URL:-https://api.openai.com/v1}"
    name: "${OPENAI_MODEL:-gpt-4o}"
    type: "llm"
    supports_tool_use: true
    provider: "openai"
    max_tokens: 32000
    context_length: 128000
    temperature: 0.7

  gpt-4.1:
    api_key: "${OPENAI_API_KEY}"
    api_base_url: "${OPENAI_API_BASE_URL:-https://api.openai.com/v1}"
    name: "${OPENAI_4_1_MODEL:-gpt-4.1}"
    type: "llm"
    supports_tool_use: true
    provider: "openai"
    max_tokens: 32000
    context_length: 128000
    temperature: 0.7

  gpt-4.1-mini:
    api_key: "${OPENAI_API_KEY}"
    api_base_url: "${OPENAI_API_BASE_URL:-https://api.openai.com/v1}"
    name: "${OPENAI_4_1_MINI_MODEL:-gpt-4.1-mini}"
    type: "llm"
    supports_tool_use: true
    provider: "openai"
    max_tokens: 32000
    context_length: 128000
    temperature: 0.7

  gpt-4.1-nano:
    api_key: "${OPENAI_API_KEY}"
    api_base_url: "${OPENAI_API_BASE_URL:-https://api.openai.com/v1}"
    name: "${OPENAI_4_1_NANO_MODEL:-gpt-4.1-nano}"
    type: "llm"
    supports_tool_use: true
    provider: "openai"
    max_tokens: 32000
    context_length: 128000
    temperature: 0.7

  o4-mini:
    api_key: "${OPENAI_API_KEY}"
    api_base_url: "${OPENAI_API_BASE_URL:-https://api.openai.com/v1}"
    name: "${OPENAI_O4_MINI_MODEL:-o4-mini}"
    type: "llm"
    supports_tool_use: true
    provider: "openai"
    max_tokens: 32000
    context_length: 128000
    temperature: 1.0

  # 豆包大模型配置
  doubao-1.5-vision-pro-32k:
    api_key: "${DOUBAO_API_KEY}"
    api_base_url: "${DOUBAO_API_BASE_URL}"
    name: "${DOUBAO_1_5_VISION_PRO_32K_MODEL:-doubao-1.5-vision-pro-32k}"
    type: "llm"
    supports_tool_use: true
    provider: "openai"
    max_tokens: 12288
    context_length: 32000
    temperature: 0.7

  doubao-1.5-pro-32k:
    api_key: "${DOUBAO_API_KEY}"
    api_base_url: "${DOUBAO_API_BASE_URL}"
    name: "${DOUBAO_1_5_PRO_32K_MODEL:-doubao-1.5-pro-32k}"
    type: "llm"
    supports_tool_use: true
    provider: "openai"
    max_tokens: 12288
    context_length: 32000
    temperature: 0.7

  doubao-1.5-pro-256k:
    api_key: "${DOUBAO_API_KEY}"
    api_base_url: "${DOUBAO_API_BASE_URL}"
    name: "${DOUBAO_1_5_PRO_256K_MODEL:-doubao-1.5-pro-256k}"
    type: "llm"
    supports_tool_use: true
    provider: "openai"
    max_tokens: 12288
    context_length: 256000
    temperature: 0.7

  doubao-1.5-thinking-pro:
    api_key: "${DOUBAO_API_KEY}"
    api_base_url: "${DOUBAO_API_BASE_URL}"
    name: "${DOUBAO_1_5_THINKING_PRO_MODEL:-doubao-1.5-thinking-pro}"
    type: "llm"
    supports_tool_use: true
    provider: "openai"
    max_tokens: 16000
    context_length: 32000

  qwen-max:
    api_key: "${QWEN_API_KEY}"
    api_base_url: "${QWEN_API_BASE_URL:-https://dashscope.aliyuncs.com/compatible-mode/v1}"
    name: "${QWEN_MODEL:-qwen-max}"
    type: "llm"
    supports_tool_use: true
    provider: "openai"
    max_tokens: 8192
    context_length: 30000
    temperature: 0.7

  qwen-long:
    api_key: "${QWEN_API_KEY}"
    api_base_url: "${QWEN_API_BASE_URL:-https://dashscope.aliyuncs.com/compatible-mode/v1}"
    name: "${QWEN_LONG_MODEL:-qwen-long}"
    type: "llm"
    supports_tool_use: true
    provider: "openai"
    max_tokens: 30000
    context_length: 64000
    temperature: 0.7

  qwen-plus:
    api_key: "${QWEN_API_KEY}"
    api_base_url: "${QWEN_API_BASE_URL:-https://dashscope.aliyuncs.com/compatible-mode/v1}"
    name: "${QWEN_PLUS_MODEL:-qwen-plus}"
    type: "llm"
    supports_tool_use: true
    provider: "openai"
    max_tokens: 8192
    context_length: 30000
    temperature: 0.7

  qwen-turbo:
    api_key: "${QWEN_API_KEY}"
    api_base_url: "${QWEN_API_BASE_URL:-https://dashscope.aliyuncs.com/compatible-mode/v1}"
    name: "${QWEN_TURBO_MODEL:-qwen-turbo}"
    type: "llm"
    supports_tool_use: true
    provider: "openai"
    max_tokens: 8192
    context_length: 16000
    temperature: 0.7

  qwq-plus:
    api_key: "${QWEN_API_KEY}"
    api_base_url: "${QWEN_API_BASE_URL:-https://dashscope.aliyuncs.com/compatible-mode/v1}"
    name: "${QWQ_PLUS_MODEL:-qwq-plus}"
    type: "llm"
    supports_tool_use: true
    provider: "openai"
    max_tokens: 8192
    context_length: 16000
    temperature: 0.7

  gemini-2.0-flash:
    api_key: "${GEMINI_API_KEY}"
    api_base_url: "${GEMINI_API_BASE_URL:-https://open.bigmodel.cn/api/paas/v4/}"
    name: "gemini-2.0-flash"
    type: "llm"
    supports_tool_use: true
    provider: "openai"
    max_tokens: 4096
    context_length: 32000
    temperature: 0.7

  gemini-2.5-pro:
    api_key: "${GEMINI_API_KEY}"
    api_base_url: "${GEMINI_API_BASE_URL:-https://open.bigmodel.cn/api/paas/v4/}"
    name: "gemini-2.5-pro-preview-03-25"
    type: "llm"
    supports_tool_use: true
    provider: "openai"
    max_tokens: 8192
    context_length: 128000
    temperature: 0.7

  gemini-2.5-pro-exp:
    api_key: "${GEMINI_API_KEY}"
    api_base_url: "${GEMINI_API_BASE_URL:-https://open.bigmodel.cn/api/paas/v4/}"
    name: "gemini-2.5-pro-exp-03-25"
    type: "llm"
    supports_tool_use: true
    provider: "openai"
    max_tokens: 8192
    context_length: 128000
    temperature: 0.7

  glm-z1-air:
    api_key: "${GLM_API_KEY}"
    api_base_url: "${GLM_API_BASE_URL:-https://open.bigmodel.cn/api/paas/v4/}"
    name: "glm-z1-air"
    type: "llm"
    supports_tool_use: true
    provider: "openai"
    max_tokens: 4096
    context_length: 16000
    temperature: 0.7

  glm-z1-airx:
    api_key: "${GLM_API_KEY}"
    api_base_url: "${GLM_API_BASE_URL:-https://open.bigmodel.cn/api/paas/v4/}"
    name: "glm-z1-airx"
    type: "llm"
    supports_tool_use: true
    provider: "openai"
    max_tokens: 8192
    context_length: 32000
    temperature: 0.7

  glm-z1-flash:
    api_key: "${GLM_API_KEY}"
    api_base_url: "${GLM_API_BASE_URL:-https://open.bigmodel.cn/api/paas/v4/}"
    name: "glm-z1-flash"
    type: "llm"
    supports_tool_use: true
    provider: "openai"
    max_tokens: 4096
    context_length: 16000
    temperature: 0.7

  glm-4-plus:
    api_key: "${GLM_API_KEY}"
    api_base_url: "${GLM_API_BASE_URL:-https://open.bigmodel.cn/api/paas/v4/}"
    name: "glm-4-plus"
    type: "llm"
    supports_tool_use: true
    provider: "openai"
    max_tokens: 8192
    context_length: 128000
    temperature: 0.7

  # Embedding模型
  magic-embedding:
    api_key: "${MAGIC_API_KEY}"
    api_base_url: "${MAGIC_API_BASE_URL:-https://api.openai.com/v1}"
    name: "${MAGIC_EMBEDDING_MODEL:-text-embedding-3-large}"
    type: "embedding"
    provider: "openai"
    max_tokens: 8192
    temperature: 0.0

  openai-embedding:
    api_key: "${OPENAI_API_KEY}"
    api_base_url: "${OPENAI_API_BASE_URL:-https://api.openai.com/v1}"
    name: "${OPENAI_EMBEDDING_MODEL:-text-embedding-3-large}"
    type: "embedding"
    provider: "openai"
    max_tokens: 8192
    temperature: 0.0

  azure-embedding:
    api_key: "${AZURE_OPENAI_EMBEDDING_API_KEY}"
    api_base_url: "${AZURE_OPENAI_EMBEDDING_ENDPOINT}"
    name: "${AZURE_OPENAI_EMBEDDING_MODEL:-text-embedding-3-large}"
    deployment: "${AZURE_OPENAI_EMBEDDING_DEPLOYMENT}"
    api_version: "${AZURE_OPENAI_EMBEDDING_API_VERSION:-2023-05-15}"
    region: "${AZURE_OPENAI_EMBEDDING_REGION:-eastus}"
    type: "embedding"
    provider: "openai"
    max_tokens: 8192
    temperature: 0.0

bing:
  search_api_key: "${BING_SUBSCRIPTION_KEY}"
  search_endpoint: "${BING_SUBSCRIPTION_ENDPOINT:-https://api.bing.microsoft.com/v7.0/search}"

filebase:
  embedding_model_id: "${FILEBASE_EMBEDDING_MODEL_ID:-magic-embedding}"
  collection_prefix: "${FILEBASE_COLLECTION_PREFIX:-SUPERMAGIC-FILEBASE}"
  max_vectorization_concurrency: "${FILEBASE_MAX_VECTORIZATION_CONCURRENCY:-20}"

token_service:
  address: "${TOKEN_SERVICE_ADDRESS}"
  redis_uri: "${REDIS_URI}"
  app_id: "${APP_ID}"
  app_secret: "${APP_SECRET}"

qdrant:
  base_uri: "${QDRANT_BASE_URI}"
  api_key: "${QDRANT_API_KEY}"
  collection_prefix: "${QDRANT_COLLECTION_PREFIX:-SUPERMAGIC-}"
  filebase_prefix: "${QDRANT_FILEBASE_PREFIX:-SUPERMAGIC-FILEBASE-}"

# TikHub配置
tikhub:
  api_key: "${TIKHUB_API_KEY}"

# 存储服务配置
storage:
  # 火山引擎TOS配置
  tos:
    host: "${TOS_HOST}"
    policy: "${TOS_POLICY}"
    algorithm: "${TOS_ALGORITHM}"
    date: "${TOS_DATE}"
    credential: "${TOS_CREDENTIAL}"
    signature: "${TOS_SIGNATURE}"
    dir: "${TOS_DIR}"
    content_type: "${TOS_CONTENT_TYPE}"

sandbox:
  id: "${SANDBOX_ID:-}"
  app_env: "${APP_ENV:-dev}"
  magic_authorization: "${MAGIC_AUTHORIZATION}"
  fetch_workspace: "${FETCH_WORKSPACE:-True}"
  agent_idle_timeout: "${AGENT_IDLE_TIMEOUT:-600}"
  idle_monitor_interval: "${IDLE_MONITOR_INTERVAL:-60}"

# 火山引擎语音配置
asr:
  app_id: "${ASR_VKE_APP_ID}"
  token: "${ASR_VKE_TOKEN}"
  cluster: "${ASR_VKE_CLUSTER}"
  secret_key: "${ASR_VKE_SECRET_KEY}"


# Magic-Space 配置
magic_space:
  api_key: "${MAGIC_SPACE_API_KEY}"
  api_base_url: "${MAGIC_SPACE_API_BASE_URL}"
