name: Build and push images

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag version'
        required: true
      task:
        description: 'Task to perform (build/publish)'
        required: true
        default: 'build'
        type: choice
        options:
          - build
          - publish
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  WEB_IMAGE: dtyq/magic-web

jobs:
  build:
    name: Build and push images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Build and push web image
        if: ${{ inputs.task == 'build' || github.event_name == 'push' }}
        run: |
          # 构建并推送服务镜像
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ env.REGISTRY }}/${{ env.WEB_IMAGE }}:${{ inputs.tag || github.ref_name }} \
            -t ${{ env.REGISTRY }}/${{ env.WEB_IMAGE }}:latest \
            --build-arg IMAGE_NAME=${{ env.REGISTRY }}/${{ env.BASE_IMAGE }} \
            -f ./Dockerfile.web \
            --push \
            ./